import { BASEURL } from '../../constants/api.constant';

export const studentEndpoints = {
  dashboard: `${BASEURL}/student/dashboard`,
  continueLearning: `${BASEURL}/student/continue-learning`,
  lessons: `${BASEURL}/student/lessons`,
  lesson: (id) => `${BASEURL}/student/lessons/${id}`,
  lessonComplete: (id) => `${BASEURL}/student/lessons/${id}/complete`,
  reviewFlashcards: `${BASEURL}/student/flashcards/review`,
  flashcardReview: (id) => `${BASEURL}/student/flashcards/${id}/review`,
  recommendations: `${BASEURL}/student/recommendations`,
  learningPath: `${BASEURL}/student/learning-path`,
  revisionPlan: `${BASEURL}/student/revision-plan`,
  history: `${BASEURL}/student/history`,
  achievements: `${BASEURL}/student/achievements`,
  studyQueue: `${BASEURL}/student/study-queue`,
  practice: `${BASEURL}/student/practice`,
  leaderboard: `${BASEURL}/student/leaderboard`,
  quizSubmit: (id) => `${BASEURL}/student/quizzes/${id}/submit`,
  quizDraft: (id) => `${BASEURL}/student/quizzes/${id}/draft`,
  chat: `${BASEURL}/student/chat`,
  chatSessions: `${BASEURL}/student/chat/sessions`,
  chatSession: (id) => `${BASEURL}/student/chat/sessions/${id}`,
  selfStudyLessons: `${BASEURL}/student/self-study/lessons`,
  selfStudyLessonsFromMaterials: `${BASEURL}/student/self-study/lessons/from-materials`,
  selfStudyMaterials: `${BASEURL}/student/self-study/materials`,
  selfStudyMaterial: (id) => `${BASEURL}/student/self-study/materials/${id}`,
  selfStudyUploadPdf: `${BASEURL}/student/self-study/materials/upload/pdf`,
  selfStudyUploadText: `${BASEURL}/student/self-study/materials/upload/text`,
  selfStudyUploadYoutube: `${BASEURL}/student/self-study/materials/upload/youtube`,
  selfStudyLessonStatus: (id) => `${BASEURL}/student/self-study/lessons/${id}/status`,
  selfStudyLessonRegenerate: (id) => `${BASEURL}/student/self-study/lessons/${id}/regenerate`,
  selfStudyLessonMaterials: (id) => `${BASEURL}/student/self-study/lessons/${id}/materials`,
  selfStudyLessonDelete: (id) => `${BASEURL}/student/self-study/lessons/${id}`,
  selfStudyFlashcards: (id) => `${BASEURL}/student/self-study/lessons/${id}/flashcards/generate`,
  selfStudyQuiz: (id) => `${BASEURL}/student/self-study/lessons/${id}/quizzes/generate`,
  notes: `${BASEURL}/student/notes`,
  note: (id) => `${BASEURL}/student/notes/${id}`,
  milestones: `${BASEURL}/student/milestones`,
  subscription: `${BASEURL}/student/subscription`,
  provisionWorkspace: `${BASEURL}/student/workspace/provision`,
  lessonGroups: `${BASEURL}/student/lesson-groups`,
  lessonGroup: (id) => `${BASEURL}/student/lesson-groups/${id}`,
  lessonGroupLessons: (id) => `${BASEURL}/student/lesson-groups/${id}/lessons`,
  lessonGroupAssign: (lessonId) => `${BASEURL}/student/lessons/${lessonId}/group`,
  selfStudyNextLesson: (id) => `${BASEURL}/student/self-study/lessons/${id}/next`,
  notifications: `${BASEURL}/notifications`,
  notificationRead: (id) => `${BASEURL}/notifications/${id}/read`,
  notificationsReadAll: `${BASEURL}/notifications/read-all`,
};
