import { BASEURL } from '../../constants/api.constant';

const BASE = `${BASEURL}/platform`;

export const platformEndpoints = {
  stats: `${BASE}/stats`,
  visits: `${BASE}/visits`,
  traffic: `${BASE}/traffic`,
  health: `${BASE}/health`,
  healthCheck: `${BASE}/health/check`,
  users: `${BASE}/users`,
  user: (id) => `${BASE}/users/${id}`,
  organizations: `${BASE}/organizations`,
  upgradePlan: (organizationId) => `${BASE}/organizations/${organizationId}/plan`,
  invoices: `${BASE}/invoices`,
  invoiceStats: `${BASE}/invoices/stats`,
  invoice: (id) => `${BASE}/invoices/${id}`,
  invoiceSend: (id) => `${BASE}/invoices/${id}/send`,
  invoicePaymentLink: (id) => `${BASE}/invoices/${id}/payment-link`,
  paymentSettings: `${BASE}/payments/settings`,
  previewUser: (userId) => `${BASE}/preview/users/${userId}`,
  previewOrganization: (orgId) => `${BASE}/preview/organizations/${orgId}`,
  content: `${BASE}/content`,
  emailAutomated: `${BASE}/email/automated`,
  emailAutomatedPauseAll: `${BASE}/email/automated/pause-all`,
  emailAutomatedTemplatePause: (key) => `${BASE}/email/automated/templates/${encodeURIComponent(key)}/pause`,
  emailAutomatedTemplateTest: (key) => `${BASE}/email/automated/templates/${encodeURIComponent(key)}/test`,
  emailTemplates: `${BASE}/email/templates`,
  emailTemplate: (id) => `${BASE}/email/templates/${id}`,
  emailPreview: `${BASE}/email/preview`,
  emailCampaigns: `${BASE}/email/campaigns`,
  emailCampaign: (id) => `${BASE}/email/campaigns/${id}`,
  emailCampaignSchedule: (id) => `${BASE}/email/campaigns/${id}/schedule`,
  emailCampaignSend: (id) => `${BASE}/email/campaigns/${id}/send`,
  emailCampaignRecoverStuck: `${BASE}/email/campaigns/recover-stuck`,
  emailLogs: `${BASE}/email/logs`,
};
