import { BASEURL } from '../../constants/api.constant';

export const organizationEndpoints = {
  dashboard: `${BASEURL}/organization/dashboard`,
  usage: `${BASEURL}/organization/usage`,
  subscription: `${BASEURL}/organization/subscription`,
  organizations: `${BASEURL}/organizations`,
  org: (id) => `${BASEURL}/organizations/${id}`,
  members: (id) => `${BASEURL}/organizations/${id}/members`,
  memberCreate: (id) => `${BASEURL}/organizations/${id}/members/create`,
  member: (id, userId) => `${BASEURL}/organizations/${id}/members/${userId}`,
  suspend: (id, userId) => `${BASEURL}/organizations/${id}/members/${userId}/suspend`,
  invites: (id) => `${BASEURL}/organizations/${id}/invites`,
  inviteAccept: `${BASEURL}/organizations/invites/accept`,
  invitePreview: `${BASEURL}/organizations/invites/preview`,
  assignments: (id) => `${BASEURL}/organizations/${id}/assignments`,
  teacherAssignment: (id) => `${BASEURL}/organizations/${id}/assignments/teacher`,
  studentAssignment: (id) => `${BASEURL}/organizations/${id}/assignments/student`,
  parentLink: (id) => `${BASEURL}/organizations/${id}/parent-links`,
  years: (orgId) => `${BASEURL}/organizations/${orgId}/academic/years`,
  terms: (orgId) => `${BASEURL}/organizations/${orgId}/academic/terms`,
  yearTerms: (orgId, yearId) => `${BASEURL}/organizations/${orgId}/academic/years/${yearId}/terms`,
  subjects: (orgId) => `${BASEURL}/organizations/${orgId}/academic/subjects`,
  subjectEnrollments: (orgId, subjectId) =>
    `${BASEURL}/organizations/${orgId}/academic/subjects/${subjectId}/enrollments`,
  topics: (orgId) => `${BASEURL}/organizations/${orgId}/academic/topics`,
  subjectTopics: (orgId, subjectId) =>
    `${BASEURL}/organizations/${orgId}/academic/subjects/${subjectId}/topics`,
  reorderTopics: (orgId, subjectId) =>
    `${BASEURL}/organizations/${orgId}/academic/subjects/${subjectId}/topics/reorder`,
  materials: `${BASEURL}/materials`,
  material: (id) => `${BASEURL}/materials/${id}`,
  materialChunks: (id) => `${BASEURL}/materials/${id}/chunks`,
  materialArchive: (id) => `${BASEURL}/materials/${id}/archive`,
  materialReprocess: (id) => `${BASEURL}/materials/${id}/reprocess`,
  materialLogs: (id) => `${BASEURL}/materials/${id}/processing-logs`,
  uploadPdf: `${BASEURL}/materials/upload/pdf`,
  uploadText: `${BASEURL}/materials/upload/text`,
  uploadYoutube: `${BASEURL}/materials/youtube`,
  lessons: `${BASEURL}/lessons`,
  lesson: (id) => `${BASEURL}/lessons/${id}`,
  lessonGenerate: `${BASEURL}/lessons/generate`,
  lessonRegenerate: (id) => `${BASEURL}/lessons/${id}/regenerate`,
  lessonSources: (id) => `${BASEURL}/lessons/${id}/sources`,
  lessonFlashcardsGenerate: (lessonId) => `${BASEURL}/lessons/${lessonId}/flashcards/generate`,
  lessonFlashcards: (lessonId) => `${BASEURL}/lessons/${lessonId}/flashcards`,
  lessonQuizGenerate: (lessonId) => `${BASEURL}/lessons/${lessonId}/quiz/generate`,
  lessonQuiz: (lessonId) => `${BASEURL}/lessons/${lessonId}/quiz`,
  lessonQuizQuestions: (lessonId) => `${BASEURL}/lessons/${lessonId}/quiz/questions`,
  analytics: (orgId) => `${BASEURL}/analytics/organization/${orgId}`,
  teacherAnalytics: `${BASEURL}/analytics/teacher`,
  analyticsFlashcardRetention: `${BASEURL}/analytics/flashcards/retention`,
  search: `${BASEURL}/search`,
  audit: `${BASEURL}/audit`,
  jobsQueues: `${BASEURL}/jobs/queues`,
  jobs: `${BASEURL}/jobs`,
  jobsFailed: `${BASEURL}/jobs/failed`,
  job: (jobId) => `${BASEURL}/jobs/${jobId}`,
  notifications: `${BASEURL}/notifications`,
  notificationRead: (id) => `${BASEURL}/notifications/${id}/read`,
  notificationsReadAll: `${BASEURL}/notifications/read-all`,
};
